import esbuild from "esbuild";
import { builtinModules } from "node:module";
import process from "process";

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
If you want to view the source, please visit the repository of this plugin.
*/
`;

const prod = process.argv[2] === "production";

// Obsidian loads `main.js` from the plugin folder, so that is where a build belongs. The override
// exists for test/integration/build/bundle.test.ts, which runs this very config to check what it
// emits: without it, `make check` would clobber whatever `make dev` had left in place.
const outfile = process.env.FLUIDITY_BUNDLE_OUTFILE ?? "main.js";

const context = await esbuild.context({
  banner: { js: banner },
  entryPoints: ["src/main.ts"],
  bundle: true,
  // Obsidian provides all of these at runtime. Bundling a second copy of any of them would not
  // merely bloat the plugin: CodeMirror's extension system keys off module identity, so a second
  // copy of @codemirror/state silently fails to interoperate with the editor's own.
  external: [
    "obsidian",
    "electron",
    "@codemirror/autocomplete",
    "@codemirror/collab",
    "@codemirror/commands",
    "@codemirror/language",
    "@codemirror/lint",
    "@codemirror/search",
    "@codemirror/state",
    "@codemirror/view",
    "@lezer/common",
    "@lezer/highlight",
    "@lezer/lr",
    ...builtinModules,
  ],
  format: "cjs",
  target: "es2021",
  logLevel: "info",
  sourcemap: prod ? false : "inline",
  treeShaking: true,
  outfile,
  minify: prod,
});

if (prod) {
  await context.rebuild();
  process.exit(0);
} else {
  await context.watch();
}
